### PR TITLE
Fix upgrade

### PR DESCRIPTION
**Pull request by Thovi98**
For an obscure reason for me, changes made at https://github.com/YunoHost-Apps/streama_ynh/pull/22 are not taken into account.

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

Ah I think I have not the rights to do this 😆

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Is this ready to merge to testing?

**Comment by Thovi98** [comment]
Yes, IMHO. I can't upgrade without it.

**Pull request merged**
